In [1]:
import numpy as np

In [ ]:
#Q1.& Q2 is there any diff in data type of variable list and arrya list ? if there is then 
#write a code to print

In [20]:
l=[1,2,3,4,5]

In [21]:
list(l)

[1, 2, 3, 4, 5]

In [ ]:
type(list(l))

In [22]:
array_list=np.array(l)

In [23]:
array_list

array([1, 2, 3, 4, 5])

In [24]:
type(array_list)

numpy.ndarray

In [8]:
#Q3. Consider the follwing changes in variable , array_list

In [30]:
array_list=np.array([1,2,3,4,5] ,2)

TypeError: Cannot interpret '2' as a data type

In [31]:
#Q4. heregiven 

In [32]:
num_array=np.array([[1,2,3] ,[4,5,6]])

In [33]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# find shape and size 

In [35]:
np.shape(num_array)

(2, 3)

In [36]:
np.size(num_array)

6

In [37]:
#Q5.- code to creat nupy array of 3*3 matrix containing zeros only, using nupay arrays creatio  fun

In [39]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#Q6-create an identity matrix of shape(5,5) using np fun

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])